USE atcms;

CREATE TABLE branch(
  id SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  title VARCHAR(255) NOT NULL,
  parentId SMALLINT(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_branch_name (name)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = FIXED;